# Generated by Django 5.1.4 on 2024-12-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactiondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('receiveraccountno', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='accountno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
