# Generated by Django 5.1.4 on 2024-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transactiondetails_remove_userdetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='type',
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='accountno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='receiveraccountno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='accountno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
