# Generated by Django 5.1.4 on 2024-12-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transactiondetails_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
    ]
